### ISSUE TITLE
UI: Filtering: Options are disorganised: grid layout might look better

### ISSUE THREAD

**Issue by ralfstrandell** [jariarkko/psgeo#107]
... but making the checkboxes line up nicely takes more space... which we really do not have on smaller mobile screens.
Investigate various possible solutions.

**Comment by ralfstrandell** [comment]
**A checkbox can be on a different line than the accompanying text.**
This causes confusion: is it a heading or trailing checkbox?

**Sorting order**
1. volcanic rocks
2. sedimentary rocks in order of solubility (sandstone > limestone/dolomite > gypsum > (salts)
3. marble
4. (other) non-volcanic, non-sedimentary rocks

and then either
5. unspecified rock
6. ice
7. earth [earth, ground, soil - which one is correct?]
8. unspecified

or alternatively a shorter list with one less problem:
5. Ice
5. Other
6. Unspecified

**Comment by jariarkko** [comment]
Yeah. The lack of nbsp is a current bug. Also, checkbox - text alignment isn't always proper. More fine-tuning needed.

**Comment by ralfstrandell** [comment]
Solved. Not elegant, but bearable. Polish later.
