### ISSUE TITLE
Concepts: Classification of rocks needs fixing

### ISSUE THREAD

**Issue by ralfstrandell** [jariarkko/psgeo#108]
The current categorization of surrounding material would benefit from fine tuning.
It needs to remain simple enough for everyone to use, though.

**problem 1: earth caves**
Glacial caves exist in moraines for example. Ice and Types of Rock are thus not sufficient categories.
**Options**: include _Earth_ as an option **or** change _Other rock_ into _Other_.
Either choice will allow earth caves to be properly included in the categories.

**problem 2: there are more than one sedimentary carbonate rocks**
Dolomite CaMg(CO3)2 is a common type of rock where karst caves form. It is different from limestone CaCO3
**Options**: two _separate entries_ (limestone, dolomite) **or** a _combined imestone/dolomite_

**problem 3: pick one from each category**
As we already have one example of silicate sedimentary rock, sandstone(s) [mudrocks ignored] and two carbonate sedimentary rocks, limestone and dolomite, then perhaps we would like to include gypsum for the sake of completeness: CaSO4 belongs to the sulphate sedimentary rocks. Gypsum karst is rare, but we have gypsum caves in our DB already. The fourth subclass would be chloride... but rock salt caves are quite transient, hence we can count them as Other.
**Options**: include _Gypsum_, **or** not.

**problem 4: Finnish bedrock is not composed of granites only**
The caves commonly labeled as "granite caves" can be enclosed in various types of granite, gneiss, migmatite, volcanic rocks, and anything "hard" and "insoluble" actually.
**Option 1**: exclusive: replace granite with _non-sedimentary, non-volcanic rock_ (unfortunately, this would include marble, but perhaps we could ignore such a small inaccuracy - everybody can see the Marble option anyway).
**Option 2**: exclusive: replace granite with _non-sedimentary, non-volcanic rock, other than marble_
**Option 3**: inclusive: [in finnish] replace granite with _syväkivet, juonikivet, metamorfiset kivet, ei marmori_ (and nobody will understand)

**Comment by jariarkko** [comment]
Yes, agreed. Needs work.

**Comment by jariarkko** [comment]
We also have issue #57 already. Maybe that should be closed and keep only this issue?
