### ISSUE TITLE
Terminology: Normative language of cave classification

### ISSUE THREAD

**Issue by ralfstrandell** [jariarkko/psgeo#110]
in psgeodb.js there is a mapping between _genetic-morphological class_ of a cave and the less exact but practical and more commonly understood _type of cave_.  The actual strings displayed are in psgeolang.js

There is some terminology and translations that could be improved, namely

- crack --> crevice **or** crevice cave

- halkeama --> rako **or** rakoluola

- crystallization --> vugg **or** blister cave

- kiteytyminen --> kideonkalo

- _optional_: consider replacing lohkare with lohkareita, lohkareikko or lohkareluola and boulders with boulder cave

Note: kideonkalo or vugg are of volcanic origin, either magmatic or hydrotermic, initially filled with liquids/gases, and later lined by crystals. Hence, crystallization is not a proper term as the cavity itself formed as a blister, and only with time got its decoration.

**Comment by ralfstrandell** [comment]
Issue #52 is included in this.

**Comment by jariarkko** [comment]
Agreed.

Maybe we can close #52 since this issue is more detailed?

**Comment by jariarkko** [comment]
Note that this issue may cover both schema and UI issues, depending on whether we want the Activity JSON to reflect this terminology change as well.
