### ISSUE TITLE
UI: Rock types: Sorting

### ISSUE THREAD

**Issue by ralfstrandell** [jariarkko/psgeo#111]
Note: this is related to issue #108 

**Logical sorting order in Filter window would be a nice touch**
1. volcanic rocks
2. sedimentary rocks in order of solubility
  2a. sandstone
  2b. limestone/dolomite
  2c. gypsum
  2d. (salts)
3. marble
4. (other) non-volcanic, non-sedimentary rocks
5. ice
6. other
7. unspecified

I might drop "salts", because such caves are very rare and volatile. I would also drop the word "other" from 4. to keep it independent of preceeding text, although that word would be nice if it were always used in proper context. Note that sedimentary mudrocks (with several subtypes) have been dropped because of no immediate need to have them.

**Comment by jariarkko** [comment]
Sorting would be good. 

But there seems to be separate issues about (a) sorting in the UI and (b) the actual schema and classification. Is this issue #111 only about a, or also about b? Didn't we have an issue for b already, maybe some of this could be added there...

Btw "6. other" stands for categories that do not fit in our classification. And "7. unknown" stands for there being no information about the rock type.  These were necessary to accommodate special cases and to accommodate the situation where the database entry simply doesn't have the info (about 40%) of cases.

**Comment by ralfstrandell** [comment]
Just sorting in the UI. Done. Was simple, and nothing much changed. Swapped some lines. No need to touch the schema.

**Comment by ralfstrandell** [comment]
b: gypsum, I assume? We could make that an issue. Btw, I just fixed it by adding one one for Rock-Gypsum. JSON schema needs to be adjusted of course.

**Comment by ralfstrandell** [comment]
The selection of rocks issue #108
