### ISSUE TITLE
Adding and fixing a cave entry might be useful to keep separate

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#115]
Currently they are behind a single link. The icon doesn't match fixing an entry, and the way that one does this may be very different for adding and fixing. Fixing in my mind is probably more like sending a message to admin that something is wrong. When adding, you need to provide a lot of info (name, coordinates, etc)

**Comment by ralfstrandell** [comment]
Good idea. Will do.

**Comment by ralfstrandell** [comment]
A simplified cave data update form was created this week and can be found here:
https://luolaseura.fi/luolaretkelle/kerro-meille/luolan-tietojen-paivitys/

It can be added to the psgeo menus, once you tell me where/how you want it. Or you can add it yourself.

**Comment by jariarkko** [comment]
The new page looks nice.

One obvious answer to your question might be "add a new button next to the add-a-cave button". 

Other more complex answers might also be possible, e.g., ability to click on a cave pin and then get information and a button to change things. But I worry that would clutter the info popups for a use case that is 1/1000th of the regular use. Probably not worth the screen estate. Currently I therefore prefer the first answer.

Thoughts?
