### ISSUE TITLE
psgeolang.js should not change when UI doesn't use a string

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#120]
For instance, if you don't need a string in the UI anymore, leave the string still in psgeolang.js. Just don't call the function to retrieve the string. Example:

    toolsAndAboutTexts["en"] = "";			// only show an icon (psgeo.js:DomainDefaults) for more info

Or, if you really are sure the string isn't needed any more in the future, delete the function, the able, etc.

**Comment by ralfstrandell** [comment]
But what if some sites want to use button text and some do not? The luolaseura.fi site, for exampe, does not use text labels on some buttons, but it may be necessary to re-enable them in the future unless the icons prove to be well understood. If each and every such change warrants a global change in codebase, we have a management nightmare.

I do understand now, that these texts were meant to be constant and not customizably by site.
Anyway, it might be a good policy not to construct messages by concatenation (->many translation issues) but to use separate message for each output.

Just to convey the idea: a simplified ecample:
msg107="Filter";  // Header in Filter window
msg023="Filter";  // Button label for the button opening Filter window
msg999="Filter"; // Header in contextual help

psgeolang.js is the only place where configuration is possible without touching the core of psgeo...

**Comment by ralfstrandell** [comment]
A good point. This would solve the issue:
**Button label visibility: set on/off in DomainDefault**

**Comment by jariarkko** [comment]
So here's the logic:

I understand it is easy to change a string file. But it may not be long-term the right thing. The strings file is a module, with a defined interface, and the strings are already today used for multiple purposes. Each string does not necessarily have just one place where it is used.

The language module should be independent of the other modules. It does not for instance know much about the context in which the language strings are needed in. It would not know anything about specialization for a particular web site variant, for instance. It just gives you strings.

If the strings need improvement => edit psgeolang.js
If the UI needs improvement => edit psgeo.js.

Note that there's a capability in psgeo.js for adding web-site specific specializations, if you need them. Add a new flag in the domainDefault structure and fill it in for the different websites. Or, if you are just making an improvement, make the improvement in psgeo.js! For instance, I think the use of icons is an improvement that should apply across all different websites.

**Comment by jariarkko** [comment]
(And now I see that you already found the domain default mechanism -- great! :-)

**Comment by jariarkko** [comment]
Fine now! Thanks!
