### ISSUE TITLE
Finlandselection has re-appeared, perhaps as part of the github mishap

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#123]

**Comment by jariarkko** [comment]
Fixed in commit e22ef7f

**Comment by jariarkko** [comment]
@ralfstrandell can we not do back-and-forth updates? If you have a reason to add something, tell me. If I have a reason to remove something, I'll tell you. But it is not productive was us to keep removing and adding the same thing. The reason that finlandselection was removed was that it was taking up space in the cramped little windows. It would be fine to add it on the filter popup, but now it is coming up on the little window. 

If we want the finland selection, then we need to do it properly, make it always appear on the filter popup. And probably not as the first thing.

(Stretch goal would be to make it more logical in the UI. Now it is kind of a double not filter. Not finland is not included...)

**Comment by jariarkko** [comment]
Here are the bugs on this that I can currently see:

1/ The filter takes up space on the upper left corner small box. Yet, it is not the most important thing to add if we had space. (Solution: move to the filter popup).

2/ On mobile version, the finland filter actually *does* come in the filter popup. But it doesn't work, it is initially set to do the filtering, even if the checkmark is not on. Solution: code needs restructuring to make the initial filter on init match the filter that is created when some checkbox is clicked. Currently that's two separate pieces of that do not agree. This was previously not a problem, but now that we added the filter popup and re-enabled the finland selection it has become an issue.

3/ Style: The "only" style looks a bit hackish. If we do it properly, it could perhaps be "[x] Finland [x] Other" or similar.

**Comment by jariarkko** [comment]
And

4/ May grow popup in mobile too large

**Comment by jariarkko** [comment]
Should be fixed in the latest update & cleanup.

**Comment by jariarkko** [comment]
So, this issue is resolved in part (it now works) but in part not (the filter should really have finland and other countries checkboxes). Leaving the issue open for that.

**Comment by ralfstrandell** [comment]
Good points.

Not all changes were based on tracked issues, and tasks were not assigned. This caused us to work on same problems, sometimes even doing opposite things. The process itself is important.

This looks good (it needs the word countries though, to look nice):

Country:
[x] Finland [x] Other countries

I can see the list growing in the coming years with one...

**Comment by jariarkko** [comment]
Yes, exactly. But now that this isn't buggy, we can take our time improving it.

**Comment by jariarkko** [comment]
Closing this and creating other issue for the nicer finland+other filter (#135)
