### ISSUE TITLE
tests fail

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#138]
Something about icons

**Comment by ralfstrandell** [comment]
Icons have moved. Forgot to change automated testing to reflect that.

**Comment by jariarkko** [comment]
yes I figured :)

**Comment by jariarkko** [comment]
I think it would be best you Ralf fixed this since you made the icon change.

**Comment by ralfstrandell** [comment]
Hadn't committed it. Fix now in repository.
