### ISSUE TITLE
i18n: replace string specific translation functions (many) with one getText(stringId)

### ISSUE THREAD

**Issue by ralfstrandell** [jariarkko/psgeo#139]
This has been completed on branch new-horizons. Needs testing in other domains beside luolaseura.fi. Can then be merged with master.

**Comment by jariarkko** [comment]
This is a good change. I will review the code though, and we need to do reviews before any major change.

**Comment by jariarkko** [comment]
Fixed as parts of @ralfstrandell's edits -- thanks!
