### ISSUE TITLE
Replacing rockTypeValueText(value) with getTextCollectionItem("rockType",value) crashes the filter window

### ISSUE THREAD

**Issue by ralfstrandell** [jariarkko/psgeo#144]

**Comment by ralfstrandell** [comment]
The problem was this:

There was a string (an array name) instead of a true reference to the array object.
Obviously, trying to access array members caused an error.

psgeolang.js: getTextCollectionItem row 948 must have
    var source = eval(controlledVocabulary + "ValueTexts");
instead of
    var source = controlledVocabulary + "ValueTexts";

**Comment by ralfstrandell** [comment]
This bug in newly introduced code affected all *ValueTexts, but is now fixed.

**Comment by jariarkko** [comment]
Good.

But I think we should probably try to avoid eval. I get nerveous when running code that I'm not entirely in control of. What's wrong with string id's being fields in some datstructure in the psgeolang. E.g.,

translations = {};
translations.and = { "en": "and", fi: "ja" };
...
getText(id) { return(translations[id][lang]); }

(Simplified a bit but i think you get the idea...)

Doing a possible reopen of this issue because of this suggestion.

**Comment by jariarkko** [comment]
(Close it again if you think we can't use this method.)

**Comment by ralfstrandell** [comment]
A good point. The new data structure is way better than the old one.

I need to do this step by step. The first step is to reduce the amount of methods by combining identical things. That has been achieved today. We have come down from about 110 methods to around 10 now. It is true that eval in general causes all kinds of grief, some security issues included (e.g. harder to detect injected malware), but I need to change the whole collection of arrays (and it's 100+) to get rid of the evals. WIll do it tomorrow. After that I will change genText and genValueText and those few functions that call these.

**Comment by ralfstrandell** [comment]
and not just
   translations1[message-id][lang]
but also, for the subactivities tags,
   translations2[vocabulary][term][lang]

**Comment by ralfstrandell** [comment]
630 lines to change

**Comment by jariarkko** [comment]
ok. sorry for causing extra work.

**Comment by ralfstrandell** [comment]
Thinkng about these translation strings... I can sort them alphabetically or leave in context-dependent order. Both options have benefits. Any preference?

**Comment by ralfstrandell** [comment]
Changes pushed. I did consider using more curly braces and indents in populating the data structures, but decided to keep things simple.

Ideally, of course, strings would go to files that we could load dynamically as needed. That would make it simpler to add translations.

**Comment by jariarkko** [comment]
I don't have a strong preference about the order.

How far are you with this overall change? Is it still in your other branch? I've been commenting on these issues, but is there a point where I could actually look at code, and is the code in your opinion complete? I don't think it makes sense for me to look before you have something that works. But once you do, i could do a review & suggest changes if needed, before we merge to main branch.

**Comment by ralfstrandell** [comment]
I have one little thing to do yet. My ajaxt/jquery getScript:s don't execute, and well, new territory. I'll study this today and this weekend we have this branch completed somehow.

**Comment by ralfstrandell** [comment]
I can throw away ajax and embed all those string definitions in psgeolang.js and have the branch completed in 60 seconds.

**Comment by jariarkko** [comment]
Which ajax calls are we talking about?

**Comment by jariarkko** [comment]
I don't think we should embed any complex ajax calls in psgeolang.js. The software structure needs to be simple. psgeolang has been and should continue to be a standalone object, with no dependencies.

If you want to parametrize the URLs that it uses, that's a different issue and needs to be dealt with differently. I don't think that needs ajax either then, but lets not bundle too many changes in one change.

**Comment by ralfstrandell** [comment]
In that case I will keep everything embedded in one file.

**Comment by jariarkko** [comment]
Cool, thanks!

**Comment by jariarkko** [comment]
(As an aside, there's room for some further files and splits of the objects. But that needs to be done in fairly well synced way, because web pages depend on our list of source files. And we need think about what's the right architecture. Not 20 new things, but maybe 1-3. Room for discussion, but lets discuss before doing.)
