### ISSUE TITLE
psgeolang: numberAlign is ineffective

### ISSUE THREAD

**Issue by ralfstrandell** [jariarkko/psgeo#145]
The function numberAlign(n,nchars) in psgeolang.js is ineffective, because it requires <pre>preformatted text</pre> and a fixed width font to have any effect. Spaces in html just evaporate....

**Comment by jariarkko** [comment]
I guess yes

**Comment by ralfstrandell** [comment]
One possible solution: table, tr, td align=right, td=align left

which is sometimes convenient but can sometimes require many columns.

Could try prepending zeros with style=invisible, or something.
...thinking...

**Comment by ralfstrandell** [comment]
what if we just enclose it in a pre tag?

**Comment by jariarkko** [comment]
I don't think the current output looks bad. Is there a need to do anything (except perhaps remove the use of align from psgeo.js)?

**Comment by jariarkko** [comment]
(Also, please remember to keep your updates specific to issues. Don't mix bug fixes with the psgeolang rewrite etc)

**Comment by ralfstrandell** [comment]
No need to do. I can remove references to nAlign from there and remove the function... or try to make it optional (by removing usage but keeping a fixed function).

**Comment by ralfstrandell** [comment]
True, bug fixes in main. This branch is only about rewrite and its direct requirements. Will leave this issue open for main branch.

**Comment by jariarkko** [comment]
Removed alignment from psgeo.js.
