### ISSUE TITLE
New-horizons branch issue: we should avoid code lines that are > 100 characters long

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#151]

**Comment by jariarkko** [comment]
E.g., in psgeolang.js getTextCollectionItem function.

**Comment by jariarkko** [comment]
Some fixes to this, but not entirely done yet.

**Comment by ralfstrandell** [comment]
A number of lines (string definitions) were put on long lines before the data structure was mangled by script. These can be put on two lines once we are happy with how they look. That won't change much, but is a bit nicer.

There are some lines of code that are too long, and can be shortened. Typically indention issues or end-of-line comments, but also some if-then statements on one line. I can fix, when you show green light.

**Comment by jariarkko** [comment]
This is now resolved (I changed a few places).  However, issue #193 was added to look at this throughout the code. Would be nice to get warnings if this happens.
