### ISSUE TITLE
Need to add/change functions in psgeolang so that adding language packs would be easy

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#174]
However, note that i have a design principle that psgeo overall should stay relatively compact and not have a ton of dependencies elsewhere.

**Comment by jariarkko** [comment]
There's a tradeoff.

We can make adding language packs possible from separate files etc. The positive is that is easier to do. The downside is that then it gets added on someone's file, and is not generally usable by other psgeo users.

I'm betting that there's not too many users and languages, and it would be better for us to keep all those translations inside our version control system and possibly even in the code. This means that we can for instance easily add new features, and all languages are easily accessible by anyone who uses them. I'd expect you to do Swedish, and maybe ... french/spanish at some point, depending on need.

I'd suggest not doing anything about this. I care more for the quality of the translations (and that they cover all features, including new ones) than the ease for someone else to add stuff.

**Comment by ralfstrandell** [comment]
Housekeeping: As this is a wontfix, I assume we can close this ticket.
