### ISSUE TITLE
About and other tools windows should have much shorter texts 

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#176]
(but still retain the relevant parts)

**Comment by ralfstrandell** [comment]
We can use boolean needShort to pick a shorter version of the text for mobile. Just add Short to the string ID...

**Comment by jariarkko** [comment]
We can use the shorter boolean, yes (that was a good idea!). But I think overall the text needs to be shorter (this issue). They are repetitive and too verbose. Particulary when we added more toools. 

Then we have another issue for even shorter for mobile (eg. might not use descriptions at all, render icons smaller, etc). That issue is #178

**Comment by ralfstrandell** [comment]
You are so correct. I would, for example, gladly strip those search word examples at first possible opportunity. First I thought it was good guidance, but then realized how much they waste space. Besides, they are a little bit patronasing...
