### ISSUE TITLE
translation for "other" given multiple times

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#177]

**Comment by ralfstrandell** [comment]
Are you sure that all these others are and remain same others?

I mean, that there will not be a future need to differentiate the words used in different contexts? Other in a menu, other in a button, other in a classification may be subject to mutually contradicting changes. It would be future proof not to translate words, but complete messages (context dependant).

**Comment by jariarkko** [comment]
It is a good question. I'm not 100% sure (could have made a mistake). But this got flagged because the new checks that I implemented complained that an identity "other" was already used. So this was not (I think) about the result text but the actual lookup key being the same. If we need different purposes, then they should have different textids... but could have made a mistake of course!
