### ISSUE TITLE
New horizon branch issue: unsure if groundType is still needed

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#179]
No one seems to be referring to this, was this only needed for the rockAndOther special case (which is now handled separately)? @ralfstrandell do you know? For the way that the special case is now handled, see the vocabulary rockTypeAndOtherMaterial code.

**Comment by ralfstrandell** [comment]
Works nicely.

GroundType (that was only needed for two little things and was a bit superfluous at present) was apparently renamed to rockTypeAndOtherMaterial and shortened. Now its name matches the naming used in psgeo.js and psgeodb.js. So this is good.

I will open a cleanup issue though, where we can discuss and consider naming conventions.
