### ISSUE TITLE
listToText may not work if it is given an empty list

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#186]
In psgeolang.js

**Comment by ralfstrandell** [comment]
It was tested to work with an empty list though.
Will take a look.

Should "empty to text" be empty or something else?

-------- Original Message --------

**Comment by jariarkko** [comment]
No worries... already fixed. I didn't actually run to an error, but it did access "list[0]". I added an if at the beginning.

**Comment by jariarkko** [comment]
There are now also tests for this and many other cases is psgeolangest.js. Found several bugs with it from psgeolang (probably these were from my earlier version, like missing strings etc).
