### ISSUE TITLE
Other tools do not yet get started with the right coordinates

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#19]

**Comment by ralfstrandell** [comment]
The **Other tools** window is a _Google Maps Infowindow_. It get automatically centered on the map.
i.e. the TIP of the infowindow get centered.

The window is too big though, and it crosses the top of the screen. This causes automatic panning to bring it back to center.
The same problem exists with **Filter window** and **More Info** windows.

There are at least three possible solutions:

1. less stuff in the window
2. vertically offset position (by how many pixels?)
3. custom overlays https://developers.google.com/maps/documentation/javascript/customoverlays

**Comment by jariarkko** [comment]
True. I've used technique 2 already for the ?p= query parameter. There's also option 1b, provide less text on smaller screens. Didn't we already do that? I think the other tools window has a full-blown and mobile version.

But "right coordinates" in this issue was not about the screen -- it was about going to the same location in that other tool, automatically. For some tools, I just not had time to program it. For others, we need coordinate conversion first.

**Comment by ralfstrandell** [comment]
I will study how various types of collapsible user interface / parts thereof could be implemented with CSS.I have an idea, but not hands-on experience yet. Expect results this month. Then we can discuss if its applicable here or not.

**Comment by jariarkko** [comment]
Maybe we can open another issue for specific popup windows (like the big other tools popup) being too big. This issue was about those other tools not being on the same coordinates.

I think the other tools popup could easily become much smaller, and this problem would go away. E.g., just include the icons (or just name) in the mobile version.

**Comment by ralfstrandell** [comment]
This issue has been resolved by a new UI.
Set psgeoDomainDefault.classicUI=false;
We use a Google Maps custom control at BOTTOM_CENTER
with some nice CSS in css/style.css
