### ISSUE TITLE
Någon dag vi borde ha svenskt språk variant

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#197]
.... and you can tell I shouldn't be making the translations :-)

**Comment by ralfstrandell** [comment]
Kan översätta, men först måste jag göra några andra saker...

**Comment by ralfstrandell** [comment]
This is soon completed, but it was a struggle among parentheses, curly braces, commas, quotation marks and semicolons.

We would still need translations at least in french and spanish to make this s/w more international, but I cannot possibly translate to these languages. And it is totally impossible to delegate the task as the translation system is something that only a programmer could love. A simple text file with string - translation pairs would be what's needed for the average translator.

**Comment by ralfstrandell** [comment]
...and done.
