### ISSUE TITLE
Remove concatenated translations

### ISSUE THREAD

**Issue by ralfstrandell** [jariarkko/psgeo#199]
Define new strings and use getTextWithValues

Most work goes into locating all these strings to change...

Problems become apparent with the swedish translation already.

**Comment by jariarkko** [comment]
Yes, and with the new {{string1}} replacement capabilities that you added, fixing this would now be possible. Cool.

**Comment by ralfstrandell** [comment]
Multipart translations (text + number + text and similar) have been removed.

While many number + space + text -type strings (eg. stat lines) could be generated by getTextWithValues alone, ... won't fix. Closing this issue.
