### ISSUE TITLE
Translation string missing: short source descriptions

### ISSUE THREAD

**Issue by ralfstrandell** [jariarkko/psgeo#200]

**Comment by ralfstrandell** [comment]
seems to be hardcoded in psgeo.

**Comment by jariarkko** [comment]
What do you refer to when you say source descriptions?

(Background info btw: I changed the psgeolang.js code so that it will give the short description if one exists, but will not fail if it doesn't exist.)

**Comment by ralfstrandell** [comment]
> (Background info btw: I changed the psgeolang.js code so that it will give the short description if one exists, but will not fail if it doesn't exist.)

Good bug fix

**Comment by ralfstrandell** [comment]
psgeo.js:
const psgeoSourcesPlain
const psgeoSourcesSwimming
const psgeoSourcesCaving
const psgeoSourcesCavingTest
const psgeoSourcesLuolaseura
- all these have a
     - name: { en: "english-text", fi: "finnish-text" }, // but no swedish or any other for that matter
     - longName similarly

const psgeoFinnishCaveClassification
has a link for english and finnish language sites, but no other languages are conted in

All these should use psgeolang.js

**Comment by ralfstrandell** [comment]
Fixed.

**Comment by jariarkko** [comment]
Saw the changes. Nice fix. Thanks!
