### ISSUE TITLE
With absolute control over data, do we really need boolean: warnedAboutNepperi and associated normalizing?

### ISSUE THREAD

**Issue by ralfstrandell** [jariarkko/psgeo#204]
The data on luolaseura.fi is, now at least, correct.

**Comment by jariarkko** [comment]
If the cave is no longer incorrectly listed in Kauniainen then we can delete this code!

**Comment by jariarkko** [comment]
(remember to pull most recent source code; i just changed psgeodb.js)

**Comment by jariarkko** [comment]
(for something else,  not for this issue)

**Comment by ralfstrandell** [comment]
Maybe tomorrow

**Comment by ralfstrandell** [comment]
Removed
