### ISSUE TITLE
psgeodb.js: normalizeItemFields: fi/en strings only -> use psgeolang.js

### ISSUE THREAD

**Issue by ralfstrandell** [jariarkko/psgeo#205]
Stuff like string variables moretexten=, moretextfi=, prefixen=, prefixfi=, typebraces= and possibly other things need internationalization using methods from psgeolang.js. These, obviously, fail in Swedish.

**Comment by ralfstrandell** [comment]
Fail kike this:

_Luolan tunniste VA5. Geneettis-morfologinen luokitus {E}. 9m,4m,4m

Koordinater: N 63.03152 E 23.99526

Längd: 17m. Typ av grotta: Sprick-._

**Comment by jariarkko** [comment]
Yep.

(Also, some the error/warning messages might need to move to psgeolang...)

**Comment by ralfstrandell** [comment]
... and done.

The real need for this part of code had been removed ages ago, as the underlying data was made to better conform to activityJSON specifications. Hence, nothing to fix. Just removed some code. NOTE Cave type must still be parsed, so that part is left untouched. The "missing translation" depends on the fact that the description fields are used in simple/legacy mode (string only). Adding english descriptions (and other languages) is a separate task, not part of psgeo coding efforts.
