### ISSUE TITLE
psgeodb.js: findFinnishCaveId and findFinnishCaveDescription are not needed anymore because the data is corrected. Functions and related normalization can be removed.

### ISSUE THREAD

**Issue by ralfstrandell** [jariarkko/psgeo#207]

**Comment by ralfstrandell** [comment]
The need for findFinnishCaveType remains.

**Comment by jariarkko** [comment]
Hmm. I don't think you have yet put the cave types in proper format in the sub activity field, or did something new happen recently? Until that happens, we need to keep the code around to map the cave types to the sub activity field.

**Comment by ralfstrandell** [comment]
There are no "Name, City [ID] {class} (something)" anymore,
but the JSON now contains "Name, City" as specified.

**Comment by ralfstrandell** [comment]
Cave types are in {class} format in the description field and they still need to be parsed. No change is planned to that.

**Comment by ralfstrandell** [comment]
The id and class are part of the textual description. The sub-activity classes are not yet complete. That is true.

**Comment by ralfstrandell** [comment]
Duplicate of #205

**Comment by jariarkko** [comment]
Tests are failing after this change, and there are a lot of very complex changes in the results. This will probably require some edits to psgeodbtest.js and testdb.res.ok. But you can't accept the output changes as is, because it was very unclear to me at least whether all of that was correct or not. I did two minor changes in test and outputs but a lot remains.

**Comment by jariarkko** [comment]
I need to go do something else now. I'll leave the rest to you :-) but you'll need to look at each difference carefully and determine why there was a change and decide whether each change needs a fix to the code, a fix to the test, or change to the expected test outputs.

**Comment by ralfstrandell** [comment]
OK will look at this at 16:00

**Comment by jariarkko** [comment]
All fixed. I think we close this now, and return to it maybe later in the year when you have added the sa-categories to the input db. (There's no urgency for that in my opinion.)
