### ISSUE TITLE
The removal of identification code has broken classification, it no longer works

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#209]
e.g. line 88 on the testdb.res

**Comment by ralfstrandell** [comment]
The difference in the merge is:

"sa":[["Rock","Rock-Granite","Morphology-Crack","Morphology-Boulders","Basic"]]
"sa":["Rock"]

versus

"sa":[["Rock","Rock-Granite","Morphology-Crack","Morphology-Boulders","Basic"]]
"sa":[["Rock"]]

The classification code has not been changed at all. There must be a default value of "Rock" somewhere that got lost.

**Comment by ralfstrandell** [comment]
**var mergetestitem3**
"sa": [["Rock","Rock-Granite","Morphology-Crack","Morphology-Boulders","Basic"]]

**var mergetestitem4**
"sa": ["Rock"]

I do not quite understand why there needs to be two ways of listing things, an array and an array containing just one array???

**Comment by jariarkko** [comment]
The two ways are because an old variant of the database used the style in mergetestitem4.

**Comment by jariarkko** [comment]
The tests now work, some code cleanup has been done, language support for finding categories has been improved, test inputs and results have been modified appropriately. 

The root cause for the errors was that
- lack of test updates and analysis of what changes a code change had
- hasty fixes (by me) to the test inputs with a typo which led to merging/classification not working

But as said, it all works now 👍
