### ISSUE TITLE
Activity JSON needs to distinguish caves in ice from ice in caves

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#210]
E.g., glacier caves and ice caves

**Comment by ralfstrandell** [comment]
Definitions by Henderson (1933) and Halliday (1966), as is reminded here:
[https://www.cambridge.org/core/journals/journal-of-glaciology/article/use-of-the-term-glacier-cave/488DFAAEC5F4C1C4D815CAD0207B622C](https://www.cambridge.org/core/journals/journal-of-glaciology/article/use-of-the-term-glacier-cave/488DFAAEC5F4C1C4D815CAD0207B622C)

**Comment by jariarkko** [comment]
Thanks!

**Comment by jariarkko** [comment]
Fixed. Planetcaver's databases have also been updated.
