### ISSUE TITLE
filter window is a bit messy on mobile

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#214]
This is because there isn't as much empty lines (and there's no space for them).

Could we put the text (e.g.,  "Koko:") and the checkboxes on the same line, for instance?

**Comment by ralfstrandell** [comment]
A) The size filtering checkboxes are self explanatory.
- remove cmpletely the header "Koko:"
- move the check boxes to the top (above name search)

B) "Luolakartalliset" can be shortened as "Kartoitetut".

C) "Luolan tyyppi" can be shortened as "Tyyppi"

**Comment by ralfstrandell** [comment]
B solved

**Comment by ralfstrandell** [comment]
C solved

**Comment by ralfstrandell** [comment]
D) The header "Suodata" is unnecessary on small displays. The dialog is dosplayed once user clicks on a magnifying glass icon (search) and the window contents are self explanatory.

**Comment by ralfstrandell** [comment]
D Solved

**Comment by jariarkko** [comment]
Cool, thanks! Will test in a day or two.

**Comment by jariarkko** [comment]
Looks great!!!!
