### ISSUE TITLE
Is it really necessary to include jquery?

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#221]
It is unclear to me if we use it, actually. Could save time by deleting the load.

**Comment by jariarkko** [comment]
See also #71, and earlier we deleted the graphs library from geo.html/kartta.html.

**Comment by jariarkko** [comment]
I think I'll just test this once I get a chance.

**Comment by jariarkko** [comment]
PsgeoInitLinkHandlers in psgeo.js uses it. Perhaps it could be written another way?

**Comment by ralfstrandell** [comment]
1) Replace quite a few "$." with "this."
2) Referencing "this" is not safe, but that is the next step to fix.
3) psgeoInitListOne calls the jQuery method getJSON

**Comment by jariarkko** [comment]
Thanks!

There's a pending psgeo rewrite where the global variables, global functions, and i hope most $'s will go away.  All variables, functions, etc will be internal to the object, not global variables hanging off $.

There's a URL resolution click function that we absolutely need though, not sure if it is possible to write that in another way.

Anyway, this isn't critical. We don't even if it takes  any time to load Jquery. I propose we wait until psgeo rewrite is done, and then re-assess.

**Comment by ralfstrandell** [comment]
Digressio extra causam:
And, oh, we are writing EcmaScript 2015, thus not supporting IE11. I can see IE used in many places, though. IE - Be gone!
https://kangax.github.io/compat-table/es6/

**Comment by ralfstrandell** [comment]
jQuery is used in psGeo to store global variables. With the current state of parameter passing to functions, removal of jQuery should not be too difficult. Did a little bit of it already.

**Comment by ralfstrandell** [comment]
Removed more global variables.
jQuery is still used on three places in psgeo.js though:
$.getJSON
$(document).on("pointerdown" ...
$(this)

**Comment by ralfstrandell** [comment]
And jQuery is gone.
Code still looks neat.
