### ISSUE TITLE
When the JSON file contains full sa-records, nothing is shown on map.

### ISSUE THREAD

**Issue by ralfstrandell** [jariarkko/psgeo#224]
e.g. Frubergsgrottan in Sweden has
"sa": [["Basic","SRT","Rock","Morphology-Boulders"]],

Not a single record on display???

**Comment by ralfstrandell** [comment]
I'm checking the preprocessor and the JSON file, but for now without results.

**Comment by ralfstrandell** [comment]
psgeodb needs some work at least (some changes in classification but there is more). Keeping old db until solved.

**Comment by ralfstrandell** [comment]
The filter and info boxes (up left, down left) are also gone. No errors on console.
Oh, there is a problem in the data. Fixing.

**Comment by jariarkko** [comment]
Ok. Let me know what you find. I am quite busy today but can do an emergency fix for psgeodb if anything got broken. But lets first find out what's happening!

**Comment by jariarkko** [comment]
I get this (it worked before, but maybe your new data has uncovered a bug):

Uncaught TypeError: rli.sa[i].push is not a function
    at addItemSubActivity (psgeodb.js:2681)
    at normalizeItemFieldsUnknownSubActivitiesOneSubActivitySet (psgeodb.js:680)
    at normalizeItemFieldsUnknownSubActivitiesOneActivity (psgeodb.js:713)
    at normalizeItemFieldsUnknownSubActivities (psgeodb.js:728)
    at normalizeItemFields (psgeodb.js:852)
    at normalizeItemGeoJSON (psgeodb.js:654)
    at normalizeItem (psgeodb.js:579)
    at normalizeDataset (psgeodb.js:886)
    at Object.addPlacesWithFilter (psgeodb.js:1432)
    at Object.success (psgeomap-suomi.js:1479)

**Comment by ralfstrandell** [comment]
push is not a function

because

rli.sa[i] is not an Array

Working on this...

**Comment by jariarkko** [comment]
Also checking...

At least for this entry:

			"n": "Pyhävuoren Peikkoluola, Alajärvi",

the sa field is wrong:

				"sa": ["Rock","Morphology-Crack","Morphology-Weathering","Morphology-Erosion"],

**Comment by jariarkko** [comment]
483 similar other entries

**Comment by jariarkko** [comment]
The field should be "sa": [["Rock", ...]]

But this did work before, because there was code that looks at an "sa" field that has a single string in an array. But now you have more than one string in the array.

**Comment by jariarkko** [comment]
The psgeodb code is now fixed, and should survive the use of inconsistent sa/a arrays. Normally, article.a.length should be exactly equal to article.sa.length. 

The fix is only to survive the data, not to correct it. The database needs an update, too.

**Comment by ralfstrandell** [comment]
The bug is in the data. Records with a reference to litterature were written incorrectly with [ ] and not [[ ]]. Hence, were pushing a string.

Debug: processing rli.sa[0] which has length: 3 and content Rock,Morphology-Boulders,Morphology-Crack
Debug: processing rli.sa[0] which has length: 4 and content Rock,Morphology-Crack,Morphology-Weathering,Morphology-Erosion
Debug: processing rli.sa[0] which has length: 1 and content Rock
Debug: processing **rli.sa[0]** which has **length: 4** and **content Rock**
TypeError: rli.sa[i].push is not a function

**Comment by ralfstrandell** [comment]
Works!

**Comment by ralfstrandell** [comment]
The caves.luolaseura.json now contans full sa-records:
- subactivity (such as Basic, SRT, ...)
- type of material (Rock, Ice, ...)
- subtype of material (Rock-*)
- morphology-*

Some finetuning will take place, but the data is there and the map works.

**Comment by jariarkko** [comment]
Great! Thanks for your work on this.

Now we have improved software to be more resilient, and have improved data. Progress!
