### ISSUE TITLE
Map is broken: ReferenceError: PsgeoDBText is not defined (and/or more)

### ISSUE THREAD

**Issue by ralfstrandell** [jariarkko/psgeo#226]
Some things are out of sync.

We have the Planetcaver scrips that say PsgeoDBText is not defined

**Comment by ralfstrandell** [comment]
In psgeodb.js: line 408: var dbText = PsgeoDBText(lib);

**Comment by ralfstrandell** [comment]
I have thus enabled locally stored scripts. They work better and display a map, but there filtering is slightly broken:
Cave type and rock type filtering has no effect.

Debug: Filter installed: ((country=Finland or not country=Finland) and (source=Suomen luolaseura or source=Planetcaver -blogi)) psgeo.js:801:13
Debug: Filter 2 pressed! psgeo.js:801:13
TypeError: db.filterMatchMultiSubActivities is not a function

**Comment by ralfstrandell** [comment]
I have now added the missing function in psgeodb.js and published it as a method and the production map @luolaseura.fi is fine now. It uses scripts stored locally at luolaseura.fi

I had to do this directly onto testing and production as the main branch is in an interesting state right now.

**Comment by jariarkko** [comment]
I guess I don't understand the error or the fix. There's no updates on the GitHub source code after 10am today, so where's the fix? Things work fine on my sites (e.g., https://planetcaver.net/geo.html or https://luolaseura.planetcaver.net/luolakartat.html).

When did we update production site?

**Comment by jariarkko** [comment]
Or is that you were pulling scripts off planetcaver.net? That would have resulted in scripts and HTML being mismatched, because the new version (which *is* deployed on planetcaver.net) requires three new .js files. I think it is a better model to have scripts in local directory in luolaseura.fi, and only update that once a week to a tagged and mutually agreed version. This means that both your and my sites and testing versions do not affect production.

I wasn't aware that we were pointing to planetcaver.net still from luolaseura.fi. Sorry for the trouble.

**Comment by ralfstrandell** [comment]
The error was this:

The map luolaseura.fi/luolakanta/kartta.html was referencing scripts on planetcaver.
When scripts and mapmap.html on planetcaver were upgraded, in sync,
the Luolaseura kartta.html was left behind.
And, because kartta.html did not reference some new files, then the map broke.

Unaware of the required changes in the page at that moment (new docs not read yet), I quickly switched to local js-files.
The local js files had another issue: I had to make minor changes to account for some changes in classification. I did these, and uploaded the scripts. Unfortunately though, I did a pull before, and got something half-ready in the mix.

**Comment by ralfstrandell** [comment]
So, all in all, this was a synchronization / communication failure, not a problem with code.

**Comment by ralfstrandell** [comment]
> Or is that you were pulling scripts off planetcaver.net?

Exactly.

This was legacy. Once in time there was agreement that Luolaseura should reference Planetcaver. It was when development was only done by you. Now that I am actively maintaining this end, the old ways are, as you say, inferior.

**Comment by ralfstrandell** [comment]
I will improve the administrative process on my behalf.

**Comment by ralfstrandell** [comment]
Scheduled releases after a feature freeze and testing is a good idea.
Given the amount of code, there is really not that much to freeze, but the idea of having a test period, even a few hours, is good.

**Comment by ralfstrandell** [comment]
I think we can close this now, if you agree.
