### ISSUE TITLE
Many warnings about unrecognised Finnish cave categories

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#227]
E.g., "WARNING: Unrecognised Finnish cave category 1"

Unclear if these are serious (probably not) or if they are a code or a data problem. Maybe code.

**Comment by ralfstrandell** [comment]
If there is a type C and a type C1, the logic stops at C, uses it, and then thinks that "1" is an invalid category.

It might be better to remove all commas and spaces etc, then prepend every _letter_ with a space.
Then this space-separated list would contain correct class strings to be analyzed.

**Comment by ralfstrandell** [comment]
addFinnishCaveCategories() gets confused

**Comment by ralfstrandell** [comment]
btw,
findFinnishCaveType() is very specific to current classification. Perhaps it mighyt work simply with {[A-Z0-9]+} pattern matching.
Not a bug, but I can see possible future maintenance work.

**Comment by ralfstrandell** [comment]
OK, half done, will be completed tomorrow

**Comment by ralfstrandell** [comment]
This function can now handle the new classes (both letter AND letter + number). Meticulous commenting added. Code cleanup.
Testing revealed a bug, that was removed. Great!
