### ISSUE TITLE
Luolaseura db's Hyyppöönvuoren Luolat, Laukaa charset is wrong

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#235]
(Error in data, not sw)

**Comment by ralfstrandell** [comment]
The source file is in UTF8, but then Putty happened, without LC_ALL=C I assume, and some characters are garbled in JSON as a result.

**Comment by ralfstrandell** [comment]
I believe this is now corrected. Awaiting confirmation.

**Comment by jariarkko** [comment]
It is now correct, verified! Thanks!
