### ISSUE TITLE
Google Maps language is explicitly set if ?lang=fi or ?lang=en exist but not if ?lang=se exists

### ISSUE THREAD

**Issue by ralfstrandell** [jariarkko/psgeo#237]
And it is fixed now.

**Comment by jariarkko** [comment]
Probably code in psgeo.js tries to look at language values (probably unnecessarily) before passing them on to psgeolang.js.

**Comment by ralfstrandell** [comment]
This specific issue has now been fixed.
I will leave related issue #112 open until discussion.

**Comment by jariarkko** [comment]
Cool, thanks!
