### ISSUE TITLE
The great SE-SV-mix: Sweden, El Salvador, Northern Sami, Swedish

### ISSUE THREAD

**Issue by ralfstrandell** [jariarkko/psgeo#238]
While
for countries   FI=Finland / EN=England / SE=Sweden / SV=El Salvador,
for languages FI=Finnish / EN=English   / SE=Northern Sami / SV=Swedish
we use
SE for Swedish.
Is this something we need to fix?

**Comment by ralfstrandell** [comment]
If I recall this correctly, we only have explicit SE in the html file(s) and in psgeolang.js where it is easy to search and replace.

**Comment by ralfstrandell** [comment]
We need to comply with standards to avoid future head aches.
The change is simple. Will fix.
Declaring this as a bug.

**Comment by jariarkko** [comment]
This is about mixing language and country codes

Country code "se" in https://www.nationsonline.org/oneworld/country_code_list.htm#S
but language code "sv" in https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

I've (perhaps mistakenly) used country codes.

Switching to language codes makes sense. 

(But one question, does browser settings know language or country?)

**Comment by ralfstrandell** [comment]
Browsers list User Preferred Languages as an ordered list. It is a user configurable thing in browser settings and it is accessible to JavaScript of course. Google Maps use it by default.

My bad. I was thinking of both SV and SE and for some reason did not look it up in the standards.

-------- Original Message --------

**Comment by jariarkko** [comment]
I do think though that if at all possible, we should be doing languages, not countries.

**Comment by ralfstrandell** [comment]
Yes, that is the plan.

-------- Original Message --------

**Comment by ralfstrandell** [comment]
...because over 60 languages are spoken in Turku alone...

Hence, countries are unsuitable selectors for language.

-------- Original Message --------

**Comment by ralfstrandell** [comment]
Search and replace done in psgeolang.js and kartta.html and tests adjusted.
Seems to work. Closing this ticket.

**Comment by jariarkko** [comment]
Great!!!!!
