### ISSUE TITLE
psgeo starts too slow. Eight seconds is a long time to wait. Major culprit is findSubsumedItems(tab)

### ISSUE THREAD

**Issue by ralfstrandell** [jariarkko/psgeo#244]
Hinted by Firefox developer tools Performance analysis, and confirmed in testing: findSubsumedItems is a problem.

Commenting out findSubsumedItems(tab); on line 938 of psgeodb.js reduces psgeo application load time from 8 sec to 3 sec.

**Comment by jariarkko** [comment]
The slow behaviour in findSubsumedItems has been corrected in commit 6b06ab7. I'm closing this issue, but understanding and optimising startup time continues to be a trackable item for other reasons.
