### ISSUE TITLE
Bombergsgrottan article cannot be found (bug in db?)

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#247]
Linkki https://luolaseura.fi/luolaretkelle/luolia-suomessa/#Bombergsgrottan ei löydy

**Comment by ralfstrandell** [comment]
There have been updates on the website and the URL has changed to
https://luolaseura.fi/luolaretkelle/suomen-luolat/#Bombergsgrottan
and it is likely to change again without warning in the future would the site be rearranged some day.

**A more resilient link would be
https://luolaseura.fi/?p=92/#Bombergsgrottan**

Can look at this / fix next week.

**Comment by jariarkko** [comment]
ok!

**Comment by ralfstrandell** [comment]
Closing an old resolved issue.
