### ISSUE TITLE
Bombergsgrottan is in Liljendal, not Lapinjärvi

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#248]
We can't fix the Suomen Luolat kirja, but maybe the luolaseura web page could be fixed. Planetcaver data is right.

**Comment by jariarkko** [comment]
Reported in a facebook discussion, see https://www.facebook.com/groups/retkipaikka/?multi_permalinks=1615438328636665&comment_id=1615895825257582&notif_id=1604477249969757&notif_t=feedback_reaction_generic&ref=notif

**Comment by jariarkko** [comment]
To be clear, the bug is in the luolaseura _article_, not the database entry.

**Comment by ralfstrandell** [comment]
FIXED

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
