### ISSUE TITLE
Add a geolocation icon

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#25]

**Comment by jariarkko** [comment]
Could you look into this @ralfstrandell ? I think Jarmo's page for instance has code that gets current location. I don't think we should always track current location (like jarmo does), but it would be nice to have a button that gets you to your current location, so that you can look what caves are around. It should probably zoom in a bit as well. But geolocation should be based on user pressing a button, rather than always. If we do it always, we get nagging questions all the time, it will become difficult to view caves in all of finland, etc.

**Comment by ralfstrandell** [comment]
Good idea. Added to work queue.

**Comment by ralfstrandell** [comment]
I will take a look at Jarmos code next week.
There is also documentation here: https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API

(where do we put the "find me" button)

**Comment by jariarkko** [comment]
One possible idea would be that it is on the main user interface, right next to the "i" button on the lower left corner.

**Comment by jariarkko** [comment]
Jarmo's code by the way does a slightly different thing. He gets the location continuously.  I'd prefer getting it only upon button press. One of the benefits of doing it this way is that we'd not get the nag-nag is geolocation allowed question to every user of the web page, only those that need geolocation.

**Comment by jariarkko** [comment]
When I was an outing earlier this week, I realized how useful this functionality would be, btw.

**Comment by ralfstrandell** [comment]
Back.

The permission question is only asked once. The browser can remember it. However, at first I will implement a button that finds out current location and centers the map, possibly with a marker there. In future iterations we can consider the watchPosition worker with an on/off toggle. But on-demand centering will come first. Note, that I've filed two other geolocation related issues, too: 2022-01-30.

**Comment by ralfstrandell** [comment]
This  _button_ has now been implemented and icon chosen. A click centers the map at current position.
