### ISSUE TITLE
Cave Association database article links are wrong

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#253]
... luolia-suomessa ... should be ... suomen-luolat ...

**Comment by jariarkko** [comment]
Partially fixed in the latest commit, by having the code fix these incorrect links. A permanent fix is needed in the database.

**Comment by jariarkko** [comment]
@RalfStrandell?

**Comment by ralfstrandell** [comment]
Ack

**Comment by ralfstrandell** [comment]
Data corrected.
