### ISSUE TITLE
Swedish language selection did not work

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#255]
Reason: confusion with regards to se/sv in the code.

Fixed now, soon to be pushed.

**Comment by ralfstrandell** [comment]
Is this issue solved now? In the HTML file there was 'sv' instead of 'en'.

**Comment by ralfstrandell** [comment]
Yes, apparently you fixed it. I did some cleanup of the code in kartta.html and am now closing this issue.
