### ISSUE TITLE
"More maps" brings up a new window which cannot be removed

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#324]
The only way to exit the more maps mode seems to be to reload the page.

Tested on computer, using Chrome

**Comment by ralfstrandell** [comment]
The More maps dialog should have a close button or link in the upper right hand corner!
Is this not the case? On what site?
This works both on planetcaver and planetswimmer sites.

**Comment by ralfstrandell** [comment]
I cannot repeat this???
Should I apply some style to the close button? Is it hidden on some site?

**Comment by ralfstrandell** [comment]
Oh, it's plain as an Old Order Amish.
Will apply some style. Moment.

**Comment by ralfstrandell** [comment]
All close buttons now have identical style, white X on blue background.
If the problem is resolved, please close the issue.
If the problem persists, let me know, and we will work on this further.
I am considering this to be resolved.

**Comment by jariarkko** [comment]
I tested this, works, thank you!
