### ISSUE TITLE
Theurbanexplorer.net map fails in Javascript error

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#327]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'op')
    at Object.matchFilter (psgeodb.js:2595:27)
    at psgeoInitMarker (psgeo.js:303:22)
    at psgeo.js:1312:9
    at Object.applyAllNoFilter (psgeodb.js:1980:13)
    at psgeoFinishLoading (psgeo.js:1311:8)
    at fetchData (psgeo.js:1202:37)

**Comment by jariarkko** [comment]
(Could be a problem in that particular website, but needs investigation)

**Comment by jariarkko** [comment]
More debugs before the error_

TIMING: finishNormalizing took 0 
psgeolib.js:919 TIMING: findSubsumedItems took 0 
psgeo.js:122 Debug: Fetching Domain Defaults from https://theurbanexplorer.net/cfg/psgeoDomainDefaults.json
psgeo.js:122 Debug: Back from fetch. Data length is 12 array elements.
psgeo.js:122 Debug: Choosing the domain default The Urban Explorer with cm = false
psgeolib.js:919 TIMING: fetch settings took 0.013 
psgeo.js:122 Debug: taking language from domain default: en
psgeo.js:122 Debug: lang: [object Object]
psgeo.js:122 Debug: window inner width 1525 and limit 800
psgeolib.js:919 TIMING: new google.maps.Map took 0.002 
psgeo.js:122 Debug: Checking topographic map selection for Finland
psgeo.js:122 Debug:    ... Finland included.
psgeo.js:122 Debug: Checking topographic map selection for Sweden
psgeo.js:122 Debug:    ... Sweden included.
psgeo.js:122 Debug: Checking topographic map selection for Norway
psgeo.js:122 Debug:    ... Norway included.
psgeo.js:122 Debug: Checking topographic map selection for UnitedKingdom
psgeo.js:122 Debug:    ... UnitedKingdom included.
psgeo.js:122 Debug: Checking topographic map selection for World
psgeo.js:122 Debug:    ... World included.
psgeolib.js:919 TIMING: initializeTopoMaps took 0 
psgeo.js:122 Debug: initImages...
psgeolib.js:919 TIMING: psgeoInitMarkerImages took 0 
psgeo.js:122 Debug: initFilterPaneControl...
psgeo.js:122 Debug: initStatsPaneControl...
psgeo.js:122 Debug: initList...
psgeo.js:122 Debug: filterForMarkers = ud
psgeo.js:122 Debug: Fetching data from https://www.planetcaver.net/locations.json
psgeo.js:122 Debug: initLinkClicks
psgeo.js:122 Debug: all initialisations done.
psgeolib.js:919 TIMING: finishNormalizing took 0.035 
psgeolib.js:919 TIMING: findSubsumedItems took 0.001 
psgeo.js:122 Debug: There are 1190 records in database after attempting/retrieving https://www.planetcaver.net/locations.json
psgeo.js:122 Debug: Loading of data has finished. There are 1190 sites now in database.
psgeo.js:122 Debug: Applying extra filterForMarkers = undef
psgeo.js:122 Debug: Applying filterForMarkers = undef

**Comment by jariarkko** [comment]
The problem is that the changes have changed the way that default filters work, and the website scripts relied on psgeo.js to have some code that did this. It no longer is there.. maybe in the configurations... needs investigation.

**Comment by jariarkko** [comment]
Same with saunablogger.cool maps
and planetclimber.net
and planetbiker.net
and planetflier.com
and planetswimmer.com

Only caving and skiing web site maps work

**Comment by ralfstrandell** [comment]
This must be a configuration issue.
Some settings in psgeoDomainDefaults.json are missing.
I will look at this.

**Comment by jariarkko** [comment]
It was a set of multiple issues... code in psgeo.js on setting filters was wrong (it didn't work for anything except skiing and caving)... some language translations were missing... and psgeoDomainDefaults.json needed some adjustment. Should be fine now.
