### ISSUE TITLE
theurbanexplorer.net map has no filter settings, except for article filter

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#328]

**Comment by ralfstrandell** [comment]
Not sure if configuration file issues qualify as a bug, but anyway...

What filtering do we want here?

I have now made:
    "articleCheckbox": true,
    "mapsCheckbox": true,
    "model3dCheckbox": true

**Comment by jariarkko** [comment]
I already fixed this ..

**Comment by ralfstrandell** [comment]
Great!

**Comment by jariarkko** [comment]
well... now we have a conflict. fixing ...

**Comment by jariarkko** [comment]
fixed.

**Comment by jariarkko** [comment]
Fixed finally in latest commit
