### ISSUE TITLE
Distance measurement tool

### ISSUE THREAD

**Issue by jarmoruuth** [jariarkko/psgeo#406]
Distance measurement tool can be used to measure distance for example from a parking lot to a cave, or just measure distance of any route.

Tool works so that the user clicks on the map to set the start position. Then the user clicks on the map to set next positions. The distance between the start position and next positions is shown in an info window.

Tool is started from a button in positionTrackingMenu. Measured distance is shown in an info window at the bottom of the map. Measuring is stopped by clicking the stop link in the info window.

Measuring uses the following events: click, touchend, bounds_changed

Function measureDistanceInit is used as an object that contains the state of the tool.

**Comment by jarmoruuth** [comment]
Code merged to Ralfs dev branch.

**Comment by ralfstrandell** [comment]
And now merged into testing.
Will take into production at Luolaseura somewhat later but still quite fast. Summer is here with all the cavíng trips.

------- Original Message -------
