### ISSUE TITLE
MML and GTK use cookies in their logo image. Can we host them to avoid this?

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#88]

**Comment by jariarkko** [comment]
See also issue #90

**Comment by ralfstrandell** [comment]
https://www.gtk.fi/wp-content/uploads/2020/01/GTK-logo.pdf (needs conversion)
https://www.maanmittauslaitos.fi/themes/custom/mml/images/suomi_logo_rgb.svg

We already host some balloons. Perhaps an /icon folder would be in order?
